export { default as CustomerReview} from './CustomerReview'
export { default as ProductInfo} from './ProductInfo'
export { default as Product} from './ProductFaq'
export { default as ProductFaq} from './ProductFaq'
export { default as ProductRelated} from './ProductRelated'
